### ISSUE TITLE
A question on the pose type

### ISSUE THREAD

**Issue by SenZHANG-GitHub** [Yuexiaoxi10/Key-Frame-Proposal-Network-for-Efficient-Pose-Estimation-in-Videos#1]
May I ask whether the pose here means human pose or camera pose? Looking forward to reading your paper after it's finally released : )

**Comment by Yuexiaoxi10** [comment]
Hi, thanks for asking question about our paper. This paper is for video-based human pose estimation problem.

**Comment by SenZHANG-GitHub** [comment]
Thanks for your reply! Looking forward to the official release of your paper : )
